#cloud-config

ssh_pwauth: false
disable_root_opts: no-port-forwarding,no-agent-forwarding,no-X11-forwarding

packages:
  - podman

package_update: true
package_upgrade: true

runcmd:
  - loginctl enable-linger $USER
  - systemctl --user enable --now podman.socket