#cloud-config

ssh_pwauth: false
disable_root_opts: no-port-forwarding,no-agent-forwarding,no-X11-forwarding

packages:
  - podman
  - podman-compose

package_update: true
package_upgrade: true

runcmd:
  - systemctl --user enable --now podman.socket